=begin
    Copyright (c) Microsoft. All rights reserved. Licensed under the MIT license. 
    See LICENSE in the project root for license information.
=end
source 'https://rubygems.org'

ruby '2.0.0'

gem 'tzinfo-data'
gem 'foreman'
gem 'thin'
gem 'rails', '4.2.1.rc2'
gem 'responders'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'pry'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
